# fly.toml file generated for boring-admin on 2023-01-05T23:52:33+02:00

app = "boring-admin"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[mounts]
  source="boring_admin_storage"
  destination="/boring_admin_storage"